### ISSUE TITLE
Not working on react-native-web

### ISSUE THREAD

**Issue by super-potion** [react-native-webrtc/react-native-webrtc#1185]
Hi there,

Currently, this package does not work on react-native-web 0.18 with react-native 0.69.

When importing react-native-webrtc, I get the following errors:
`TypeError: Object(...) is not a function at ./node_modules/react-native-webrtc/lib/module/ScreenCapturePickerView.js`
`Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.`
`Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.`

I tried installing react-native-webrtc-web-shim, and got the same errors with and without react-native-webrtc-web-shim installed and imported. 

After installing using npm install, I am importing:
`import {
  ScreenCapturePickerView,
  RTCIceCandidate,
  RTCSessionDescription,
  RTCView,
  MediaStream,
  MediaStreamTrack,
  mediaDevices,
  registerGlobals,
} from "react-native-webrtc";`

and no additional setup.

Are there additional setup steps for react-native-web that I've missed or am I correct in that the plugin isn't working on web?

#### Platform Information

* **React Native Version**: 0.69
* **Plugin Version**: 1.100.0
* **OS**:  Web
* **OS Version**: Tired in latest versions of Chrome and Firefox

**Comment by saghul** [comment]
ScreenCapturePickerView is not available on web. There is no equivalent, so there never will be.

**Comment by super-potion** [comment]
> ScreenCapturePickerView is not available on web. There is no equivalent, so there never will be.

I see. Even after removing ScreenCapturePickerView from the import, the same error is thrown on web. Is there any work around or is this package no longer working on web?

**Comment by saghul** [comment]
This package should be used on web, the shim should provide the same API.

This plugin is just for mobile devices.
