### ISSUE TITLE
I have some errors please help me 

### ISSUE THREAD

**Issue by mertbuldur** [react-native-webrtc/react-native-webrtc#727]
Hi i dont install webrtc in my react native project.I have some errors this errors is here 
`WebRTCModule+VideoTrackAdapter.m:7:9: 'React/RCTBridge.h' file not found
 RCTWebRTC/WebRTCModule.h:11:9: 'React/RCTBridgeModule.h' file not found
`

I follow this document https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

**Comment by sesm** [comment]
@mertbuldur Could you please create a new React Native project (with the same version of RN that you have in you current project), and try to reproduce the problem there? 
If the problem is reproduced, please create a repo with this new project on GitHub and post the link here.
Thanks!

**Comment by saghul** [comment]
Ignore that document. Sorry about that I’m going to make adjustments ASAP. In RN 0.60 linking is no longer necessary.

**Comment by OriAmir** [comment]
@saghul I have the same problem. I follow all the steps from ios installation and get this error on build. what can I do about that?
thanks!

**Comment by gummigiovannie** [comment]
Could anyone got it working on iOS using the latest React Native? I was able to successfully build using React Native 0.59 and the document https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md

**Comment by mertbuldur** [comment]
@saghul  hi , What was the latest state of development?  thanks , best regards.

**Comment by saghul** [comment]
State of what exactly?

**Comment by hennessywill** [comment]
Hi saghul, he is referring to your previous comment about making adjustments to the iOS installation instructions given that linking is no longer necessary in RN 0.60.

I just created a fresh project following the iOS instructions with RN 0.62.2 and react-native-webrtc 1.75.3 and receive the same build error as mertbuldur:

/Users/willhennessy/MyWebrtcDemo/node_modules/react-native-webrtc/ios/RCTWebRTC/WebRTCModule+RTCDataChannel.m:3:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.

![Screen Shot 2020-05-16 at 2 54 16 AM](https://user-images.githubusercontent.com/5455577/82114208-eed67080-9720-11ea-9623-16d668be3968.png)

I notice that RCTBridge.h is not included in WebRTC.framework/Headers - perhaps that's the cause?

Do you understand what's going wrong? Or would you please be able to update the iOS installation instructions for RN 0.62?

Thanks!

**Comment by s-mikulich** [comment]
Hi! I have the same problem as @hennessywill. @hennessywill, did you resolve this problem?

**Comment by s-mikulich** [comment]
@saghul, could you check the problem, please?
"react": "16.11.0",
 "react-native": "0.62.2",
 "react-native-webrtc": "1.75.2"
Thanks.
